# Generated by Django 3.0.4 on 2020-04-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200412_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recruitment_article',
            field=models.BooleanField(default=False),
        ),
    ]
