# Generated by Django 3.0.4 on 2020-04-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200422_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentpost',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
